[tool.ruff]

select = [
    "E",  # pycodestyle errors
    "F",  # pyflakes
    "I",  # isort
    "N",  # pep8-naming
]

ignore = []

line-length = 88

exclude = [
    ".git",
    ".venv",
    "venv",
    "build",
    "dist",
]

target-version = "py39"

[tool.black]
line-length = 88
target-version = ['py39']
include = '\.pyi?$'
extend-exclude = '''
/(
    \.git
  | \.venv
  | venv
  | build
  | dist
)/
'''
